networks:
  app-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/16
          gateway: 172.30.0.1

volumes:
  postgres_data_development:
  pdf_tmpfs:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs

services:
  # :: Greenmail service for email testing ::
  greenmail:
    image: greenmail/standalone:2.1.3
    networks:
      - app-network
    ports:
      - "25025:3025"   # SMTP
      - "25143:3143"   # IMAP
      - "25465:3465"   # SMTPS
      - "25993:3993"   # IMAPS
      - "25181:8080"   # Web UI
    environment:
      - GREENMAIL_OPTS=
        -Dgreenmail.setup.test.all
        -Dgreenmail.hostname=0.0.0.0
        -Dgreenmail.users=greenmail-user:EzUVrHxLVrF2@dev.offpost.no,public-entity:KjMnBvCxZq9Y@dev.offpost.no

  # :: Roundcube service with MySQL backend ::
  roundcube:
    image: roundcube/roundcubemail:1.4.x-apache
    networks:
      - app-network
    depends_on:
      - mysql
    links:
      - mysql
      - greenmail:greenmail
    ports:
      - "25080:80"
    volumes:
      - ./organizer/src/username-password.php:/username-password.php
      - ./organizer/src/username-password-override-dev.php:/username-password-override.php
      - ./roundcubemail.config.php:/var/roundcube/config/config.email-engine.inc.php
    environment:
      - ROUNDCUBEMAIL_DB_TYPE=mysql
      - ROUNDCUBEMAIL_DB_HOST=mysql
      - ROUNDCUBEMAIL_DB_USER=mail
      - ROUNDCUBEMAIL_DB_PASSWORD=mail
      - ROUNDCUBEMAIL_DB_NAME=roundcubemail

  mysql:
    image: mysql:5.6
    networks:
      - app-network
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: roundcubemail
      MYSQL_USER: mail
      MYSQL_PASSWORD: mail

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    networks:
      - app-network
    ports:
      - "25082:80"
    links:
      - mysql:db


  # :: Organizer service with PostgreSQL backend ::
  postgres:
    image: postgres:15
    networks:
      - app-network
    environment:
      POSTGRES_DB: offpost
      POSTGRES_USER: offpost
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    volumes:
      - postgres_data_development:/var/lib/postgresql/data
      - ./secrets/postgres_password:/run/secrets/postgres_password:ro
    ports:
      - "25432:5432"

  adminer:
    image: adminer:5.3.0
    networks:
      - app-network
    ports:
      - "25084:8080"
    depends_on:
      - postgres
    links:
      - postgres:postgres
    environment:
      - ADMINER_DEFAULT_SERVER=postgres

  organizer:
    build: ./organizer
    networks:
      - app-network
    ports:
      - "25081:80"
    depends_on:
      - postgres
    links:
      - postgres:postgres
      - mysql:mysql
      - auth:auth
      - greenmail:greenmail
    volumes:
      - ./organizer/src/username-password-override-dev.php:/username-password-override.php
      - ./organizer/src:/php-frontend
      - /php-frontend/vendor
      - ./data/:/organizer-data
      - ./data/entities.json:/organizer-data/entities.json
      - ./secrets/postgres_password:/run/secrets/postgres_password:ro
      - ./secrets/openai_api_key:/run/secrets/openai_api_key:ro
      - pdf_tmpfs:/tmp/pdf_extraction
    environment:
      - ENVIRONMENT=development
      - IMAP_SERVER={greenmail:3993/imap/ssl}
      - IMAP_EMAIL=greenmail-user
      - IMAP_PASSWORD=EzUVrHxLVrF2
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=offpost
      - DB_USER=offpost
      - DB_PASSWORD_FILE=/run/secrets/postgres_password

  auth:
    build:
      context: ./auth
      args:
        NODE_ENV: development
    networks:
      - app-network
    ports:
      - "25083:3000"
    volumes:
      - ./data/users:/data/users
      - ./auth:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - OIDC_ISSUER_URL=http://localhost:25083
      - OIDC_CLIENT_ID=organizer
      - OIDC_CLIENT_SECRET=secret
      - OIDC_REDIRECT_URI=http://localhost:25081/callback
