networks:
  app-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/16
          gateway: 172.30.0.1

services:
  roundcube:
    image: roundcube/roundcubemail:1.4.x-apache
    networks:
      - app-network
    links:
      - mysql
    ports:
      - "25080:80"
    volumes:
      - ./organizer/src/username-password.php:/username-password.php
      - /opt/offpost/username-password-override-prod.php:/username-password-override.php
      - ./roundcubemail.config.php:/var/roundcube/config/config.email-engine.inc.php
    restart: unless-stopped

  mysql:
    image: mysql:5.6
    networks:
      - app-network
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: roundcubemail
      MYSQL_USER: mail
      MYSQL_PASSWORD: mail
    restart: unless-stopped

  organizer:
    build: ./organizer
    networks:
      - app-network
    ports:
      - "25081:80"
    links:
      - mysql:mysql
    volumes:
      - /opt/offpost/username-password-override-prod.php:/username-password-override.php
      - ./organizer/src:/php-frontend
      - /opt/offpost/data/:/organizer-data
    environment:
      - ENVIRONMENT=production
    restart: unless-stopped
