roundcube:
  image: roundcube/roundcubemail
  links:
    - mysql
  ports:
    - "25080:80"
#  environment:
#    ROUNDCUBEMAIL_DSNW: mysql://mail:mail@mysql/roundcubemail
#    ROUNDCUBEMAIL_SMTP_SERVER: tls://smtp.sendgrid.net
#    ROUNDCUBEMAIL_SMTP_PORT: 587
#    ROUNDCUBEMAIL_DEFAULT_HOST: ssl://imap.one.com:993/imap/ssl
#    ROUNDCUBEMAIL_DEFAULT_PORT: 993
  volumes:
    - ./organizer/src/username-password-smtp.php:/username-password-smtp.php
    - ./roundcubemail.config.php:/var/www/html/config/config.inc.php

mysql:
  image: mysql:5.6
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: roundcubemail
    MYSQL_USER: mail
    MYSQL_PASSWORD: mail

phpmyadmin:
  image: phpmyadmin/phpmyadmin
  ports:
    - "25082:80"
  links:
    - mysql:db

organizer:
  build: ./organizer
  ports:
    - "25081:80"
  links:
    - mysql:mysql
  volumes:
    - ./organizer/src:/php-frontend
    - ./data/:/organizer-data