networks:
  app-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/16
          gateway: 172.30.0.1

volumes:
  postgres_data:
  pdf_tmpfs:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs

services:
  roundcube:
    image: roundcube/roundcubemail:1.4.x-apache
    networks:
      - app-network
    links:
      - mysql
    ports:
      - "25080:80"
    volumes:
      - ./organizer/src/username-password.php:/username-password.php
      - /opt/offpost/secrets/username-password-override-prod.php:/username-password-override.php
      - ./roundcubemail.config.php:/var/roundcube/config/config.email-engine.inc.php
    restart: unless-stopped

  mysql:
    image: mysql:5.6
    networks:
      - app-network
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: roundcubemail
      MYSQL_USER: mail
      MYSQL_PASSWORD: mail
    restart: unless-stopped

  postgres:
    image: postgres:15
    networks:
      - app-network
    environment:
      POSTGRES_DB: offpost
      POSTGRES_USER: offpost
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - /opt/offpost/secrets/postgres_password:/run/secrets/postgres_password:ro
      - /opt/offpost/secrets/openai_api_key:/run/secrets/openai_api_key:ro
    restart: unless-stopped

  organizer:
    build: ./organizer
    networks:
      - app-network
    ports:
      - "25081:80"
    depends_on:
      - postgres
    links:
      - postgres:postgres
      - mysql:mysql
    volumes:
      - /opt/offpost/secrets/username-password-override-prod.php:/username-password-override.php
      - ./organizer/src:/php-frontend
      - /php-frontend/vendor
      - /opt/offpost/data/:/organizer-data
      - ./data/entities.json:/organizer-data/entities.json
      - /opt/offpost/secrets/postgres_password:/run/secrets/postgres_password:ro
      - pdf_tmpfs:/tmp/pdf_extraction
    environment:
      - ENVIRONMENT=production
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=offpost
      - DB_USER=offpost
      - DB_PASSWORD_FILE=/run/secrets/postgres_password
    restart: unless-stopped

  cron:
    build: ./cron-scheduler
    networks:
    - app-network
    restart: unless-stopped
