version: '3'

services:
  roundcube:
    image: roundcube/roundcubemail:1.4.x-apache
    links:
      - mysql
    ports:
      - "25080:80"
    volumes:
      - ./organizer/src/username-password-smtp.php:/username-password-smtp.php
      - ./roundcubemail.config.php:/var/roundcube/config/config.email-engine.inc.php

  mysql:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: roundcubemail
      MYSQL_USER: mail
      MYSQL_PASSWORD: mail

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "25082:80"
    links:
      - mysql:db

  organizer:
    build: ./organizer
    ports:
      - "25081:80"
    links:
      - mysql:mysql
      - auth:auth
    volumes:
      - ./organizer/src:/php-frontend
      - ./data/:/organizer-data
    environment:
      - AUTH_URL=http://localhost:25083
      - ENVIRONMENT=development

  auth:
    build:
      context: ./auth
      args:
        NODE_ENV: development
    ports:
      - "25083:3000"
    volumes:
      - ./data/users:/data/users
      - ./auth:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - OIDC_ISSUER_URL=http://localhost:25083
      - OIDC_CLIENT_ID=organizer
      - OIDC_CLIENT_SECRET=secret
      - OIDC_REDIRECT_URI=http://localhost:25081/callback.php
